### ISSUE TITLE
how to Change the font style？

### ISSUE THREAD

**Issue by zzz9h** [xTeJk/Fall_Guys_Internal#2]
how to Change the font style？

**Comment by xTeJk** [comment]
If you want to change font then:

Find in `imgui/imgui_draw.cpp`:
```
        ImFormatString(font_cfg.Name, IM_ARRAYSIZE(font_cfg.Name), "ProggyClean.ttf, %dpx", (int)font_cfg.SizePixels);
```

And replace `ProggyClean.ttf` to whatever font you want, which is installed on your pc.
For example:
`ProggyClean.ttf` -> `arialbd.ttf`
