### ISSUE TITLE
get an assertion failure?

### ISSUE THREAD

**Issue by LonelyLinear** [xTeJk/Fall_Guys_Internal#5]
![image](https://user-images.githubusercontent.com/46360272/90591756-7e207380-e1a9-11ea-9cf2-71347e4b5166.png)

Please tell me how to fix it, Thanks!

**Comment by LonelyLinear** [comment]
After I injected .dll, I press insert key and then showing this error.

**Comment by LonelyLinear** [comment]
OK, I fix it by dashing the line it told me, but I'm not sure if I'm doing right.

**Comment by xTeJk** [comment]
Already fixed, thanks for report
